#!/bin/bash



RED="\033[31m"
NOC="\033[0m"

fib() {
  number=11
  x=0
  y=1
  i=2
  while [ $i -lt $number ]
  do
  i=`expr $i + 1`
  z=`expr $x + $y`
  echo -e "$REDОтвет: $z$NOC"
  x=$y
  y=$z
  done
}

fib | tail -1
