first-release:
    rm -f first.exe
    as -g first.s -o first.o
    ld first.o -o first.exe
    rm first.o

first-debug:
    as -g first.s -o first.o
    ld first.o -o first.exe
    gdb first.exe
    rm first.o first.exe

second-release:
    rm -f second.exe
    as -g second.s -o second.o
    ld second.o -o second.exe
    rm second.o

second-debug:
    as -g second.s -o second.o
    ld second.o -o second.exe
    gdb second.exe
    rm second.o second.exe
