default:
    just --list

set shell := ["bash", "-cu"]

alias b := build
alias c := clean

src := "main.s"
obj := "main.o"
exe := "main.a"
lst := "main.l"

clean name:
    @rm -f {{ name }}/{{ obj }} {{ name }}/{{ exe }} {{ name }}/{{ lst }}

build name:
    @just clean {{ name }}
    @as -adhln -g {{ name }}/{{ src }} -o {{ name }}/{{ obj }} > {{ name }}/{{ lst }}
    @mold {{ name }}/{{ obj }} -o {{ name }}/{{ exe }}
    @gdb {{ name }}/{{ exe }} -ex "b _start" -ex "b exit" -ex "lay regs" -ex "r" -q
