set shell := ["bash", "-cu"]

alias b := build
alias c := clean

src := "main.s"
obj := "main.o"
exe := "main.a"
lst := "main.l"

clean name:
    rm -f {{ name }}/{{ obj }} {{ name }}/{{ exe }} {{ name }}/{{ lst }}

build name:
    just clean {{ name }}
    as -adhln -g {{ name }}/{{ src }} -o {{ name }}/{{ obj }} > {{ name }}/{{ lst }}
    ld {{ name }}/{{ obj }} -o {{ name }}/{{ exe }}
    gdb {{ name }}/{{ exe }} -ex "break _start" -ex "lay regs"
